"""add profile to users

Revision ID: 0bdae0df2609
Revises: 79c5c33aca99
Create Date: 2024-10-17 13:30:17.078888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdae0df2609'
down_revision: Union[str, None] = '79c5c33aca99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.Enum('CLIENT', 'CONTRACTOR', name='profile'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
